import { Asset, NewsItem, Signal, DataSource, Settings } from '@/types';

export const mockAssets: Asset[] = [
  { id: '1', symbol: 'BTC', name: 'Bitcoin', type: 'crypto', watchlisted: true },
  { id: '2', symbol: 'ETH', name: 'Ethereum', type: 'crypto', watchlisted: true },
  { id: '3', symbol: 'SOL', name: 'Solana', type: 'crypto', watchlisted: true },
  { id: '4', symbol: 'AAPL', name: 'Apple Inc.', type: 'stock', watchlisted: true },
  { id: '5', symbol: 'TSLA', name: 'Tesla Inc.', type: 'stock', watchlisted: false },
  { id: '6', symbol: 'NVDA', name: 'NVIDIA Corp.', type: 'stock', watchlisted: false },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    source: 'Bloomberg',
    headline: 'Bitcoin ETF sees record inflows amid institutional adoption surge',
    content: 'Major cryptocurrency exchange-traded funds recorded unprecedented inflows this week as institutional investors continue to embrace digital assets...',
    assets: [mockAssets[0]],
    sentiment_label: 'Bullish',
    sentiment_score: 0.85,
    relevance_score: 92,
    fundamental_score: 88,
    status: 'used_in_signal',
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    source: 'Reuters',
    headline: 'Federal Reserve hints at potential rate cuts in Q2',
    content: 'The Federal Reserve Chairman suggested in today\'s testimony that monetary policy adjustments may be warranted...',
    assets: [mockAssets[0], mockAssets[1]],
    sentiment_label: 'Bullish',
    sentiment_score: 0.72,
    relevance_score: 85,
    fundamental_score: 79,
    status: 'processed',
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    source: 'Coindesk',
    headline: 'Ethereum network upgrade faces unexpected delays',
    content: 'Core developers announced a postponement of the next major network upgrade due to critical testing issues...',
    assets: [mockAssets[1]],
    sentiment_label: 'Bearish',
    sentiment_score: -0.65,
    relevance_score: 78,
    fundamental_score: 42,
    status: 'processed',
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    source: 'The Block',
    headline: 'Solana DeFi TVL reaches all-time high',
    content: 'Total value locked in Solana decentralized finance protocols surged past previous records...',
    assets: [mockAssets[2]],
    sentiment_label: 'Bullish',
    sentiment_score: 0.78,
    relevance_score: 88,
    fundamental_score: 83,
    status: 'used_in_signal',
  },
  {
    id: '5',
    timestamp: new Date(Date.now() - 18000000).toISOString(),
    source: 'CNBC',
    headline: 'Apple reports strong iPhone sales in emerging markets',
    content: 'Tech giant Apple exceeded analyst expectations with robust revenue growth...',
    assets: [mockAssets[3]],
    sentiment_label: 'Bullish',
    sentiment_score: 0.68,
    relevance_score: 75,
    fundamental_score: 71,
    status: 'used_in_signal',
  },
];

export const mockSignals: Signal[] = [
  {
    id: '1',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    asset: mockAssets[0],
    timeframe: '4h',
    total_score: 86,
    fundamental_score: 88,
    technical_score: 84,
    onchain_score: 82,
    rating: 'Strong Buy',
    entry_price: 67500,
    target_price: 72000,
    stop_loss: 65000,
    risk_level: 'Medium',
    status: 'Active',
    holding_period: 'Swing',
    strategy: 'Aggressive',
    source_news: [mockNews[0]],
    notes: 'Strong bullish momentum with ETF inflows',
  },
  {
    id: '2',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    asset: mockAssets[2],
    timeframe: '1d',
    total_score: 81,
    fundamental_score: 83,
    technical_score: 79,
    onchain_score: 78,
    rating: 'Buy',
    entry_price: 145.50,
    target_price: 165.00,
    stop_loss: 138.00,
    risk_level: 'Medium',
    status: 'Active',
    holding_period: 'Position',
    strategy: 'Moderate',
    source_news: [mockNews[3]],
  },
  {
    id: '3',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    asset: mockAssets[3],
    timeframe: '1h',
    total_score: 74,
    fundamental_score: 71,
    technical_score: 77,
    onchain_score: 72,
    rating: 'Buy',
    entry_price: 178.25,
    target_price: 183.50,
    stop_loss: 175.80,
    risk_level: 'Low',
    status: 'Hit Target',
    holding_period: 'Day trade',
    strategy: 'Cautious',
    source_news: [mockNews[4]],
  },
  {
    id: '4',
    created_at: new Date(Date.now() - 14400000).toISOString(),
    asset: mockAssets[1],
    timeframe: '4h',
    total_score: 45,
    fundamental_score: 42,
    technical_score: 48,
    onchain_score: 46,
    rating: 'Neutral',
    entry_price: 3550,
    target_price: 3650,
    stop_loss: 3480,
    risk_level: 'Medium',
    status: 'Active',
    holding_period: 'Swing',
    strategy: 'Cautious',
    source_news: [mockNews[2]],
  },
  {
    id: '5',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    asset: mockAssets[0],
    timeframe: '1d',
    total_score: 88,
    fundamental_score: 85,
    technical_score: 91,
    onchain_score: 87,
    rating: 'Strong Buy',
    entry_price: 65200,
    target_price: 70000,
    stop_loss: 63000,
    risk_level: 'Low',
    status: 'Hit Target',
    holding_period: 'Swing',
    strategy: 'Aggressive',
    source_news: [mockNews[0], mockNews[1]],
  },
];

export const mockDataSources: DataSource[] = [
  {
    id: '1',
    name: 'Bloomberg',
    type: 'news',
    status: 'Online',
    reliability_score: 95,
    weight_in_fundamental: 0.25,
    last_fetch_at: new Date(Date.now() - 300000).toISOString(),
    configured_keywords: ['bitcoin', 'ethereum', 'crypto', 'fed', 'rates'],
    is_enabled: true,
  },
  {
    id: '2',
    name: 'Reuters',
    type: 'news',
    status: 'Online',
    reliability_score: 93,
    weight_in_fundamental: 0.22,
    last_fetch_at: new Date(Date.now() - 420000).toISOString(),
    configured_keywords: ['market', 'trading', 'finance', 'economy'],
    is_enabled: true,
  },
  {
    id: '3',
    name: 'Coindesk',
    type: 'news',
    status: 'Online',
    reliability_score: 88,
    weight_in_fundamental: 0.18,
    last_fetch_at: new Date(Date.now() - 180000).toISOString(),
    configured_keywords: ['crypto', 'blockchain', 'defi', 'nft'],
    is_enabled: true,
  },
  {
    id: '4',
    name: 'The Block',
    type: 'news',
    status: 'Degraded',
    reliability_score: 85,
    weight_in_fundamental: 0.15,
    last_fetch_at: new Date(Date.now() - 7200000).toISOString(),
    configured_keywords: ['crypto', 'web3', 'blockchain'],
    is_enabled: true,
  },
  {
    id: '5',
    name: 'CNBC',
    type: 'news',
    status: 'Online',
    reliability_score: 90,
    weight_in_fundamental: 0.20,
    last_fetch_at: new Date(Date.now() - 600000).toISOString(),
    configured_keywords: ['stocks', 'market', 'earnings', 'tech'],
    is_enabled: true,
  },
];

export const mockSettings: Settings = {
  fundamental_threshold: 65,
  weight_fundamental: 0.6,
  weight_technical: 0.4,
  total_score_to_rating_mapping: {
    strong_buy: [80, 100],
    buy: [65, 79],
    neutral: [40, 64],
    sell: [25, 39],
    strong_sell: [0, 24],
  },
  default_timeframe: '4h',
  default_assets: ['BTC', 'ETH', 'AAPL'],
  notification_channels: {
    email: true,
    telegram: false,
    slack: false,
    webhook: false,
  },
  user_timezone: 'UTC',
};
