import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { CouncilVerdictBadge } from "./CouncilVerdictBadge";
import { CouncilAgreementBar } from "./CouncilAgreementBar";
import { AlertTriangle, Scale } from "lucide-react";
import type { SignalCouncilSummary } from "@/types/council";

interface SignalCouncilModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  summary: SignalCouncilSummary | null;
  assetSymbol?: string;
}

export function SignalCouncilModal({
  open,
  onOpenChange,
  summary,
  assetSymbol,
}: SignalCouncilModalProps) {
  if (!summary) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Scale className="h-5 w-5 text-primary" />
            AI Council Summary
            {assetSymbol && (
              <span className="text-muted-foreground font-normal">• {assetSymbol}</span>
            )}
          </DialogTitle>
          <DialogDescription>
            Generated by {summary.modelCount} AI models with {summary.agreement}% agreement
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 pt-2">
          {/* Verdict Section */}
          <div className="flex items-center justify-between">
            <span className="text-sm text-muted-foreground">Final Verdict</span>
            <CouncilVerdictBadge verdict={summary.verdict} />
          </div>

          {/* Agreement Bar */}
          <CouncilAgreementBar
            agreement={summary.agreement}
            verdict={summary.verdict}
          />

          {/* Confidence */}
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Confidence</span>
            <span className="font-medium">{summary.confidence}%</span>
          </div>

          {/* Reasoning */}
          <div className="pt-2 border-t border-border">
            <h4 className="text-sm font-medium mb-2">Why this signal exists</h4>
            <p className="text-sm text-muted-foreground">{summary.reasoning}</p>
          </div>

          {/* Top Risks */}
          <div className="pt-2 border-t border-border">
            <h4 className="text-sm font-medium mb-2 flex items-center gap-1.5">
              <AlertTriangle className="h-4 w-4 text-neutral" />
              Top Risks
            </h4>
            <ul className="space-y-1.5">
              {summary.topRisks.map((risk, idx) => (
                <li key={idx} className="text-sm text-muted-foreground flex gap-2">
                  <span className="text-neutral">•</span>
                  <span>{risk}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
